# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSoyYo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire',                            '4.9.0'
  pod 'lottie-ios',                           '3.1.8'
  pod 'SDWebImage',                           '5.6.1'

  # Pods for TestSoyYo

  target 'TestSoyYoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
